### PR TITLE
Use a custom User Agent when retrieving the remote revision files

### LINKED ISSUE #13: Set a User Agent for requests made to external resources
Currently the requests use a generic User Agent, eg:
> "GET /revision.txt?cachescramble=1463055296.49 HTTP/1.0" 200 41 "-" "Python-urllib/1.17"

I'll open a PR for this.

### PR DESCRIPTION
**Pull request by edmorley**
Also switches to using the much more pleasant requests library.

Fixes #13.

### CODE REVIEW

**Comment by peterbe** [comment]
AWESOME!

**Comment by edmorley** [comment]
Thank you :-)
Do you know when this might be deployed?

**Comment by peterbe** [comment]
I just did. Seconds ago. Does it work as expected?

**Comment by edmorley** [comment]
Yup working well, thank you :-)

```
[17/May/2016:19:47:49 +0000] "GET /revision.txt?cachescramble=1463514469.26 HTTP/1.1" 200 59 "-" "whatsdeployed"
```

**Pull request merged**
