### PR TITLE
Culprits dismount

### LINKED ISSUE #75: Culprits dismount
Start loading a deployment page. E.g. `http://localhost:3000/s/xXq`
Before waiting for the Culprits thing to fully load, click the home "What's Deployed" link at the top. 

screen shot 2019-02-15 at 12 10 25 pm

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #75

Sucks to have to do that `if (this.dismounted) return;` logic in three different places. Ideas to refactor that? ...if any necessary.

### CODE REVIEW

**Comment by mythmon** [comment]
> Ideas to refactor that?

I think we need a much more cohesive approach to loading data that can handle with cancelling things. I'm not sure what that looks like today, but once React Hooks and Suspense are fully baked, maybe that? It seems to automatically handle this.

**Comment by mythmon** [comment]
> but once React Hooks and Suspense are fully baked

Also, maybe we can jump ahead and start using the alpha versions of that. I'd be ok with that, if you are.

**Comment by peterbe** [comment]
> alpha version of that ... ok with that, if you are.

You mean of suspense? Heck yeah. Things like that is what makes it worthwhile bothering with projects like whatsdeployed.

**Comment by peterbe** [comment]
By the way, one thing I've come to appreciate is that doing fetch cancellation is almost entirely unrelated to watching out for dismounts. All it means is that the `catch(ex)` will trigger around the the `await fetch()`. 

So I was naughty in this PR by mixing two different "features" in one PR. Sorry  :) But again, wateveh'.

**Pull request merged**
