### PR TITLE
deployment basics

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by peterbe** [comment]
@mythmon So it's not perfect but does a good job. One thing I know for sure is that I don't want to run `yarn run build` on the server. 
If these scripts are good enough, we could copy-n-paste it into a job on CircleCI that pushes out build artefacts that we either store there (at first pass) and then ship them somewhere (e.g. GitHub Releases).

**Comment by peterbe** [comment]
> adding the version parsing stuff over complicates this PR

true, but it works and it's not particularly critical. 

> You also committed the zip file, which I think you shouldn't do.

That's the intention. To start. I think we criss-crossed our communication. Either

1. We land this, scripts plus `build.zip`. Then some day we write some CircleCI code that generates the `build.zip` and stores it in some good place. 

2. We land this but only the scripts. Then, as soon as possible, we write some CircleCI code that generates the `build.zip` and stores it in some good place.

**Comment by mythmon** [comment]
I'm generally against checking build artifacts into the repo. I think that even if we don't have CI integration, we shouldn't put the zip in the repository. We can put it on the releases page manually, or simply scp them around. Either way, I'm r- on checking the zip file into the repository.

**Comment by peterbe** [comment]
Yeah, it ain't pretty but it's practical. I guess, now if we have CircleCI that could be a good place. On the server, I can make it do a wget + unzip from GitHub as part of the deployment script.

**Comment by peterbe** [comment]
Ok. Next we need a script to upload releases to GitHub. I can work on that.

**Pull request merged**
